Repository JOBPREP-BE/JOBPREP-BE, pull requests merged in 2024-12, with the labels that each got.

#6 Feat/#58 job interview api design
  src/main/java/io/dev/jobprep/common/swagger/template/JobInterviewSwagger.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerJobInterviewErrorExamples.java
  src/main/java/io/dev/jobprep/domain/job_interview/application/JobInterviewService.java
  src/main/java/io/dev/jobprep/domain/job_interview/domain/JobInterview.java
  src/main/java/io/dev/jobprep/domain/job_interview/domain/enums/DefaultJobInterview.java
  src/main/java/io/dev/jobprep/domain/job_interview/domain/enums/JobInterviewCategory.java
  src/main/java/io/dev/jobprep/domain/job_interview/exception/JobInterviewException.java
  src/main/java/io/dev/jobprep/domain/job_interview/infrastructure/JobInterviewRepository.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/JobInterviewController.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/req/PutJobInterviewRequest.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/res/FindJobInterviewResponse.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/res/JobInterviewIdResponse.java
  src/main/resources/db/migration/V9__CHANGE_ENUM_JOB_INTERVIEW_CATEGORY.sql
Labels: ⭐️ Feat

#7 Feat/#59 study domain (+study swagger)
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerStudyErrorExamples.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyScheduleService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/application/dto/res/StudyInfoDto.java
  src/main/java/io/dev/jobprep/domain/study/application/dto/res/StudyWithStartDateDto.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/Study.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/StudySchedule.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/UserStudy.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/enums/Position.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/enums/StudyStatus.java
  src/main/java/io/dev/jobprep/domain/study/exception/StudyException.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustomImpl.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyScheduleJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/UserStudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/presentation/StudyController.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyCreateRequest.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyScheduleCreateRequest.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyUpdateAdminRequest.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyUpdateRequest.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyCommonResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyIdResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyInfoAdminResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyInfoResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyScheduleInfoResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyUpdateAdminResponse.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/res/StudyUpdateResponse.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode403.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode404.java
  src/main/resources/db/migration/V3__CHANGE_STUDY_NAME_UNIQUE.sql
  src/main/resources/db/migration/V4__DROP_USER_STUDY_AND_ADD_STUDY_ID_TO_USER.sql
  src/main/resources/db/migration/V5__CHANGE_ENUM_FOR_STUDY_STATUS.sql
  src/main/resources/db/migration/V6__CHAHGE_ENUM_FOR_STUDY_POSITION.sql
  src/main/resources/db/migration/V7__ADD_USER_STUDY_AND_DROP_STUDY_ID_TO_USER.sql
Labels: ⭐️ Feat

#9 [FIX] user 도메인 패키지 위치 수정
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/Study.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/UserStudy.java
Labels: 🐞 Bug

#13 [FIX] 테이블 pk 컬럼 AUTO_INCREMENT로 수정, flyway version up to 11
  src/main/resources/db/migration/V11__CHANGE_ID_TO_AUTO_INCREMENT.sql
Labels: 🐞 Bug

#11 Feat/#63 application status domain (+application status swagger)
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerApplicationStatusErrorExamples.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/application/ApplicationStatusService.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/ApplicationStatus.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProcess.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProgress.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/exception/ApplicationStatusException.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/infrastructure/ApplicationStatusJpaRepository.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/req/ApplicationStatusCreateRequest.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/req/ApplicationStatusUpdateRequest.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusCommonResponse.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusIdResponse.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusInfoResponse.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusUpdateResponse.java
  src/main/java/io/dev/jobprep/exception/GlobalExceptionHandler.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode403.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode404.java
  src/main/java/io/dev/jobprep/util/LocalDateTimeConverter.java
  src/main/resources/db/migration/V10__CHANGE_COMPANY_LINK_TO_URL_FOR_APPLICATION_STATUS.sql
Labels: ⭐️ Feat

#12 Refact/#70 study domain update with user domain
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerStudyErrorExamples.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerUserErrorExamples.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyCommonService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyScheduleService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/Study.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/UserStudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyCreateRequest.java
  src/main/java/io/dev/jobprep/domain/users/domain/User.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode403.java
Labels: 🔄 Refactor

#16 [REFACT] 임시 사용자 인증을 위한 @RequestParam 추가 (추후에 JWT 토큰 인증 방식으로 변경)
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/study/presentation/StudyController.java
Labels: 🔄 Refactor

#17 Infra/#43 임시 jenkins cd pipeline
  Jenkinsfile
  src/test/java/io/dev/jobprep/JobprepApplicationTests.java
Labels: 🚀 Infra

#19 [TEST] jenkins test를 위한 주석 추가
  src/main/java/io/dev/jobprep/domain/study/domain/entity/Study.java
Labels: 🧪 TEST

#21 [TEST] HeapDumpOnOutOfMemory 해결을 위한 gradle.properties 추가
  gradle.properties
Labels: 🐞 Bug

#24 Bug/#75 fix study api
  src/main/java/io/dev/jobprep/domain/study/application/StudyScheduleService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/Study.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyCreateRequest.java
  src/main/java/io/dev/jobprep/domain/study/presentation/dto/req/StudyScheduleCreateRequest.java
  src/main/java/io/dev/jobprep/util/LocalDateTimeConverter.java
Labels: 🐞 Bug

#27 Bug/#78 application status api
  src/main/java/io/dev/jobprep/domain/applicationstatus/application/ApplicationStatusService.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/ApplicationStatus.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProcess.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProgress.java
  src/main/resources/db/migration/V13__CHANGE_ENUM_APPLICATION_STATUS.sql
Labels: 🐞 Bug

#29 [BUG] application_status API에 id 필드 추가
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusCommonResponse.java
Labels: 🐞 Bug

#31 [REFACT] application_status 도메인 enum 타입 컬럼 default 제거, 조회 필드에 coverLetter 추가
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProcess.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/enums/ApplicationProgress.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusCommonResponse.java
  src/main/resources/db/migration/V14__REMOVE_APPLICATION_STATUS_DEFAULT.sql
Labels: 🔄 Refactor

#35 [BUG] 스터디 시작일자 관련 500 에러를 400 에러로 포장
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
Labels: 🐞 Bug

#36 [FEAT] 지원현황 생성 레코드에 자기소개서 필드 추가
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/req/ApplicationStatusCreateRequest.java
Labels: 🔄 Refactor

#34 Feat/#76 실시간 채팅을 위한 chat 도메인 API 개발, 채팅 읽음 여부 기능 추가 개발, 컨테이너 환경 구축, 커서 기반, 오프셋 기반 페이지네이션 적용
  build.gradle
  docker-compose.yml
  src/main/java/io/dev/jobprep/common/base/CursorPaginationReq.java
  src/main/java/io/dev/jobprep/common/base/CursorPaginationResult.java
  src/main/java/io/dev/jobprep/common/base/OffsetPaginationReq.java
  src/main/java/io/dev/jobprep/common/base/OffsetPaginationResult.java
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/ChatSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/configuration/RedisConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebSocketConfig.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerChatErrorExamples.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/application/ApplicationStatusService.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/infrastructure/ApplicationStatusJpaRepository.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/infrastructure/ApplicationStatusRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/infrastructure/ApplicationStatusRepositoryCustomImpl.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatCommonService.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatRedisService.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatService.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatWSService.java
  src/main/java/io/dev/jobprep/domain/chat/application/SequenceGenerator.java
  src/main/java/io/dev/jobprep/domain/chat/application/dto/res/ChatMessageCommonInfo.java
  src/main/java/io/dev/jobprep/domain/chat/application/dto/res/ChatRoomCommonInfo.java
  src/main/java/io/dev/jobprep/domain/chat/domain/entity/document/ChatMessage.java
  src/main/java/io/dev/jobprep/domain/chat/domain/entity/document/ChatRoom.java
  src/main/java/io/dev/jobprep/domain/chat/domain/entity/document/ChatUser.java
  src/main/java/io/dev/jobprep/domain/chat/domain/entity/document/SequenceId.java
  src/main/java/io/dev/jobprep/domain/chat/domain/entity/enums/ChatRoomStatus.java
  src/main/java/io/dev/jobprep/domain/chat/exception/ChatException.java
  src/main/java/io/dev/jobprep/domain/chat/infrastructure/ChatMongoRepository.java
  src/main/java/io/dev/jobprep/domain/chat/interceptor/StompInterceptor.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/ChatRoomController.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/ChatWSController.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/dto/req/ChatMessageRequest.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/dto/res/ChatMessageCommonResponse.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/dto/res/ChatRoomAdminResponse.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/dto/res/ChatRoomIdResponse.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/dto/res/ChatUserCommonResponse.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustomImpl.java
  src/main/java/io/dev/jobprep/domain/study/presentation/StudyController.java
  src/main/java/io/dev/jobprep/domain/users/application/dto/res/UserCommonInfo.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode403.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode404.java
  src/main/java/io/dev/jobprep/util/LocalDateTimeConverter.java
  src/main/java/io/dev/jobprep/util/LongParsingProvider.java
  src/main/resources/db/migration/V18__DROP_CHAT_MESSAGES_TABLE.sql
Labels: ⭐️ Feat

#43 Feat/#95 job interview, exp master cl pagination 적용
  src/main/java/io/dev/jobprep/common/swagger/template/ExpMasterClSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/JobInterviewSwagger.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/application/ExpMasterClService.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/infrastructure/ExpMasterClRepository.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/infrastructure/ExpMasterClRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/infrastructure/ExpMasterClRepositoryCustomImpl.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/ExpMasterClController.java
  src/main/java/io/dev/jobprep/domain/job_interview/application/JobInterviewService.java
  src/main/java/io/dev/jobprep/domain/job_interview/infrastructure/JobInterviewRepository.java
  src/main/java/io/dev/jobprep/domain/job_interview/infrastructure/JobInterviewRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/job_interview/infrastructure/JobInterviewRepositoryCustomImpl.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/JobInterviewController.java
Labels: 🔄 Refactor

#44 Feat/#186 scheduling for study (+ internal API 호출 제한을 위한 IP white-list 관리)
  build.gradle
  src/main/java/io/dev/jobprep/common/alert/mail/PrettyPrintHelper.java
  src/main/java/io/dev/jobprep/common/alert/mail/handler/MailHandler.java
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/configuration/MailConfig.java
  src/main/java/io/dev/jobprep/core/configuration/RetryConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebMvcConfig.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerStudyErrorExamples.java
  src/main/java/io/dev/jobprep/domain/alert/application/AlertReportService.java
  src/main/java/io/dev/jobprep/domain/alert/exception/AlertException.java
  src/main/java/io/dev/jobprep/domain/alert/slack/application/SlackAlertService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyCommonService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyScheduleService.java
  src/main/java/io/dev/jobprep/domain/study/domain/entity/StudySchedule.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyJpaRepository.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode401.java
  src/main/java/io/dev/jobprep/scheduler/StudyAutoDeletionScheduler.java
  src/main/java/io/dev/jobprep/system/internal/developer/DeveloperTokenHelper.java
  src/main/java/io/dev/jobprep/system/internal/developer/token/DevToken.java
  src/main/java/io/dev/jobprep/system/internal/exception/InternalException.java
  src/main/java/io/dev/jobprep/system/internal/interceptor/IpWhiteListInterceptor.java
  src/main/java/io/dev/jobprep/system/internal/presentation/SystemInternalController.java
  src/main/java/io/dev/jobprep/system/internal/whitelist/application/WhiteListManager.java
  src/main/java/io/dev/jobprep/system/internal/whitelist/domain/entity/WhiteList.java
  src/main/java/io/dev/jobprep/system/internal/whitelist/infrastructure/WhiteListJpaRepository.java
  src/main/java/io/dev/jobprep/util/IpAddressHelper.java
  src/main/resources/db/migration/V20__ADD_WHITE_LIST.sql
  src/main/resources/schedule_sql/delete_study_for_3_duration_weeks_after_12.sql
  src/main/resources/schedule_sql/delete_study_for_short_on_member_after_12.sql
  src/main/resources/schedule_sql/study_in_progress_after_12.sql
Labels: ⭐️ Feat
