Repository JOBPREP-BE/JOBPREP-BE, pull requests merged in 2025-01, with the labels that each got.

#45 Refact/#92 transaction for chat (+ cursor-based-pagination 확장) (+진행중)
  .gitignore
  docker-compose.yml
  scripts/backup_for_docker.sh
  scripts/restore_for_docker.sh
  src/main/java/io/dev/jobprep/common/base/BaseCursorPaginationReq.java
  src/main/java/io/dev/jobprep/common/base/LongCursorPaginationReq.java
  src/main/java/io/dev/jobprep/common/base/StringCursorPaginationReq.java
  src/main/java/io/dev/jobprep/common/event/WebSocketMonitoringEventListener.java
  src/main/java/io/dev/jobprep/common/stomp/StompTokenProcessor.java
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/ChatSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/ExpMasterClSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/JobInterviewSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/configuration/MongoConfig.java
  src/main/java/io/dev/jobprep/core/configuration/RedisConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebSocketConfig.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatRedisService.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatService.java
  src/main/java/io/dev/jobprep/domain/chat/application/dto/res/ChatRoomCommonInfo.java
  src/main/java/io/dev/jobprep/domain/chat/infrastructure/ChatMongoRepository.java
  src/main/java/io/dev/jobprep/domain/chat/interceptor/StompInterceptor.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/ChatRoomController.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/ChatWSController.java
  src/main/java/io/dev/jobprep/domain/essentialMaterial/presentation/dto/EssentialMaterialController.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/ExpMasterClController.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/JobInterviewController.java
  src/main/java/io/dev/jobprep/domain/study/presentation/StudyController.java
  src/main/java/io/dev/jobprep/exception/GlobalExceptionHandler.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode404.java
  src/main/java/io/dev/jobprep/util/LongParsingProvider.java
  src/main/resources/logback-spring.xml
Labels: 🔄 Refactor

#48 Refact/#223 set logback per profile
  .gitignore
  build.gradle
  src/main/java/io/dev/jobprep/common/logging/LoggingInterceptor.java
  src/main/java/io/dev/jobprep/common/logging/aspect/LogExecutionTimeAspect.java
  src/main/java/io/dev/jobprep/common/logging/aspect/annotation/LogExecutionTime.java
  src/main/java/io/dev/jobprep/common/logging/mdc/MDCRequestLoggingFilter.java
  src/main/java/io/dev/jobprep/core/configuration/AopConfig.java
  src/main/java/io/dev/jobprep/core/configuration/JdbcConfig.java
  src/main/java/io/dev/jobprep/core/configuration/JpaConfig.java
  src/main/java/io/dev/jobprep/core/configuration/MongoConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebMvcConfig.java
  src/main/java/io/dev/jobprep/domain/alert/application/AlertReportService.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/application/ApplicationStatusService.java
  src/main/java/io/dev/jobprep/domain/essentialMaterial/application/EssentialMaterialService.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/application/ExpMasterClService.java
  src/main/java/io/dev/jobprep/domain/job_interview/application/JobInterviewService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyCommonService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyScheduleService.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/users/application/AdminCommonService.java
  src/main/java/io/dev/jobprep/domain/users/application/UserCommonService.java
  src/main/java/io/dev/jobprep/domain/users/application/UserService.java
  src/main/java/io/dev/jobprep/scheduler/StudyAutoDeletionScheduler.java
  src/main/java/io/dev/jobprep/system/internal/whitelist/application/WhiteListManager.java
  src/main/resources/logback-spring.xml
  src/main/resources/schedule_sql/delete_study_for_3_duration_weeks_after_12.sql
  src/main/resources/schedule_sql/delete_study_for_short_on_member_after_12.sql
  src/main/resources/schedule_sql/study_in_progress_after_12.sql
Labels: 🔄 Refactor

#53 Refact/#221 optimize offset based pagination
  scripts/generate_dummy_data.py
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/ChatSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/EssentialMaterialSwagger.java
  src/main/java/io/dev/jobprep/core/configuration/MongoConfig.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/application/ApplicationStatusService.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/domain/entity/ApplicationStatus.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/req/ApplicationStatusCreateRequest.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusCommonResponse.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/dto/res/ApplicationStatusInfoResponse.java
  src/main/java/io/dev/jobprep/domain/study/application/StudyService.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyJpaRepository.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustom.java
  src/main/java/io/dev/jobprep/domain/study/infrastructure/StudyRepositoryCustomImpl.java
  src/main/resources/db/migration/V21__CHANGE_NULL_FOR_APPLICATION_STATUS.sql
  src/main/resources/db/migration/V22__ADD_COVERING_INDEX_FOR_STUDY.sql
Labels: 🔄 Refactor

#50 Feat/#217 api 양식 통일
  src/main/java/io/dev/jobprep/common/swagger/template/ExpMasterClSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/JobInterviewSwagger.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/application/ExpMasterClService.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/domain/ExpMasterCl.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/ExpMasterClController.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/dto/req/ExpMasterClPatchRequest.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/dto/res/ExpMasterClIdResponse.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/dto/res/FindExpMasterClResponse.java
  src/main/java/io/dev/jobprep/domain/experience_master_cl/presentation/dto/res/UpdateExpMasterClResponse.java
  src/main/java/io/dev/jobprep/domain/job_interview/application/JobInterviewService.java
  src/main/java/io/dev/jobprep/domain/job_interview/domain/JobInterview.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/JobInterviewController.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/req/PutJobInterviewRequest.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/res/JobInterviewIdResponse.java
  src/main/java/io/dev/jobprep/domain/job_interview/presentation/dto/res/UpdateJobInterviewResponse.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
Labels: 🔄 Refactor

#49 Feat/#89 리프레쉬 토큰 캐싱 로직 구현 (진행중)
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/io/dev/jobprep/common/swagger/template/OauthSwagger.java
  src/main/java/io/dev/jobprep/core/configuration/SecurityConfig.java
  src/main/java/io/dev/jobprep/core/configuration/ServerConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebConfig.java
  src/main/java/io/dev/jobprep/core/properties/swagger/error/SwaggerJwtErrorExamples.java
  src/main/java/io/dev/jobprep/domain/chat/application/ChatService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/AuthService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/JwtRedisService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/JwtService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/dto/TokenInfo.java
  src/main/java/io/dev/jobprep/domain/security/jwt/exception/TokenException.java
  src/main/java/io/dev/jobprep/domain/security/jwt/filter/JwtAccessDeniedHandler.java
  src/main/java/io/dev/jobprep/domain/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/io/dev/jobprep/domain/security/oauth/application/OAuth2SuccessHandler.java
  src/main/java/io/dev/jobprep/domain/security/oauth/presentation/OauthController.java
  src/main/java/io/dev/jobprep/domain/security/util/TokenHeaderConstants.java
  src/main/java/io/dev/jobprep/domain/users/application/AdminCommonService.java
  src/main/java/io/dev/jobprep/domain/users/domain/User.java
  src/main/java/io/dev/jobprep/domain/users/domain/UserRole.java
  src/main/java/io/dev/jobprep/exception/GlobalExceptionHandler.java
  src/main/java/io/dev/jobprep/exception/code/ErrorCode400.java
  src/main/resources/db/migration/V23__REFACTOR_USER_ROLES.sql
Labels: ⭐️ Feat

#56 [INFRA] Window 환경을 위한 mongodb.key 권한 체킹하는 서비스 추가
  docker-compose.yml
Labels: 🚀 Infra

#57 Refact/#239 apply authentication with token
  src/main/java/io/dev/jobprep/common/auth/JwtToken.java
  src/main/java/io/dev/jobprep/common/auth/resolver/JwtTokenAnnotationResolver.java
  src/main/java/io/dev/jobprep/common/swagger/template/ApplicationStatusSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/ChatSwagger.java
  src/main/java/io/dev/jobprep/common/swagger/template/StudySwagger.java
  src/main/java/io/dev/jobprep/core/configuration/SecurityConfig.java
  src/main/java/io/dev/jobprep/core/configuration/WebMvcConfig.java
  src/main/java/io/dev/jobprep/domain/applicationstatus/presentation/ApplicationStatusController.java
  src/main/java/io/dev/jobprep/domain/chat/presentation/ChatRoomController.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/AuthService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/JwtService.java
  src/main/java/io/dev/jobprep/domain/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/io/dev/jobprep/domain/security/oauth/application/CustomOAuth2UserService.java
  src/main/java/io/dev/jobprep/domain/security/oauth/application/PrincipalDetailsService.java
  src/main/java/io/dev/jobprep/domain/security/oauth/domain/PrincipalDetails.java
  src/main/java/io/dev/jobprep/domain/study/presentation/StudyController.java
  src/main/java/io/dev/jobprep/domain/users/presentation/UserController.java
Labels: 🔄 Refactor

#68 [REFACT] Stomp 연결을 위한 임시 헤더 검증 제거, accessToken 기반 검증으로 변경
  src/main/java/io/dev/jobprep/common/stomp/StompTokenProcessor.java
  src/main/java/io/dev/jobprep/domain/security/jwt/application/JwtService.java
Labels: 🔄 Refactor

#73 [INFRA] Create integration-test.yml
  .github/workflows/integration-test.yml
Labels: 🚀 Infra

#75 Infra/#246 reconstruct health check endpoint ( + Blue-Green 배포 활용 무중단 배포 )
  src/main/java/io/dev/jobprep/common/actuator/ApplicationHealthIndicator.java
  src/main/java/io/dev/jobprep/common/actuator/MutableHealthIndicator.java
  src/main/java/io/dev/jobprep/system/internal/health/HealthCheckController.java
Labels: 🚀 Infra

#76 [REFACT] health-check를 위해 간단한 내부 API 호출을 수행하도록 변경
  src/main/java/io/dev/jobprep/common/actuator/ApplicationHealthIndicator.java
  src/main/java/io/dev/jobprep/system/internal/health/HealthCheckController.java
Labels: 🔄 Refactor

#77 Infra/#248 set micrometer for prometheus
  .github/workflows/integration-test.yml
  build.gradle
  src/main/java/io/dev/jobprep/domain/security/jwt/filter/JwtAuthenticationFilter.java
Labels: 🚀 Infra

#78 [REFACT] promtail에서 관리할 애플리케이션 로그 파일 경로 및 패턴 변경
  src/main/resources/logback-spring.xml
Labels: 🚀 Infra, 🔄 Refactor
